[package]
edition = "2018"
name = "palindrome-products"
version = "1.2.0"

[dev-dependencies]
criterion = "0.3"

[profile.release]
debug = true

[[bench]]
name = "my_benchmark"
harness = false
debug = true
